export const seedAssurances = [
  { name: 'Assurance Allianz' },
  { name: 'Atlanta' },
  { name: 'AMO' },
  { name: 'AXA Assurance Maroc' },
  { name: 'CNSS' },
  { name: 'CNOPS' },
  { name: 'Mutuelle de la Police' },
  { name: 'Mutuelle des Banques Populaires' },
  { name: 'Mutuelle des Douanes' },
  { name: 'FAR' },
  { name: 'MGPTT' },
  { name: 'MGEN' },
  { name: 'MGPAP' },
  { name: 'OMFAM' },
  { name: 'RMA Watanya' },
  { name: 'SAHAM' },
  { name: 'Wafa Assurance' },
  { name: 'CNIA' },
  { name: 'MAMDA' },
  { name: 'MCMA' },
  { name: 'Sanad' },
];
