import type { Brand } from './types';

export const seedBrands: Omit<Brand, 'id'>[] = [
  // Premium
  { name: 'Dior', category: 'Premium' },
  { name: 'Gucci', category: 'Premium' },
  { name: 'Prada', category: 'Premium' },
  { name: 'Miu Miu', category: 'Premium' },
  { name: 'Tom Ford', category: 'Premium' },
  { name: 'Cartier', category: 'Premium' },
  { name: 'Saint Laurent', category: 'Premium' },
  { name: 'Fendi', category: 'Premium' },
  { name: 'Loewe', category: 'Premium' },
  { name: 'Celine', category: 'Premium' },
  { name: 'Chloé', category: 'Premium' },
  { name: 'Balenciaga', category: 'Premium' },
  { name: 'Dolce & Gabbana', category: 'Premium' },
  { name: 'Burberry', category: 'Premium' },
  { name: 'Versace', category: 'Premium' },
  { name: 'Alexander McQueen', category: 'Premium' },
  { name: 'Moncler', category: 'Premium' },
  { name: 'Chanel', category: 'Premium' },
  { name: 'Bvlgari', category: 'Premium' },
  // Populaires
  { name: 'Ray-Ban', category: 'Populaire' },
  { name: 'Oakley', category: 'Populaire' },
  { name: 'Carrera', category: 'Populaire' },
  { name: 'Persol', category: 'Populaire' },
  { name: 'Calvin Klein', category: 'Populaire' },
  { name: 'Hugo Boss', category: 'Populaire' },
  { name: 'Diesel', category: 'Populaire' },
  { name: 'Guess', category: 'Populaire' },
  { name: 'Carolina Herrera', category: 'Populaire' },
  { name: 'David Beckham', category: 'Populaire' },
  { name: 'Converse', category: 'Populaire' },
  { name: 'Emporio Armani', category: 'Populaire' },
  // Françaises
  { name: 'Anne & Valentin', category: 'Française' },
  { name: 'Caroline Abram', category: 'Française' },
  { name: 'JF Rey', category: 'Française' },
  { name: 'Lesca', category: 'Française' },
  { name: 'Vuarnet', category: 'Française' },
  { name: 'OXIBIS', category: 'Française' },
  { name: 'Atelier Particulier', category: 'Française' },
  { name: 'Jimmy Fairly', category: 'Française' },
  { name: 'Alain Mikli', category: 'Française' },
  // Autres
  { name: 'Matsuda', category: 'Autre' },
  { name: 'Masunaga', category: 'Autre' },
  { name: 'Moscot', category: 'Autre' },
  { name: 'Garrett Leight', category: 'Autre' },
  { name: 'Oliver Peoples', category: 'Autre' },
  { name: 'Cutler and Gross', category: 'Autre' },
  { name: 'Etnia Barcelona', category: 'Autre' },
  { name: 'Kirk Original', category: 'Autre' },
  { name: 'Bollé', category: 'Autre' },
  { name: 'OXYDO', category: 'Populaire' },
  { name: 'PIERRE CARDIN', category: 'Populaire' },
  { name: 'PIERRE LOTI', category: 'Française' },
  { name: 'PLUS', category: 'Autre' },
  { name: 'POLAR', category: 'Populaire' },
  { name: 'Polarised', category: 'Populaire' },
  { name: 'POLAROID', category: 'Populaire' },
  { name: 'POLICE', category: 'Populaire' },
  { name: 'PUCCI', category: 'Premium' },
  { name: 'Ralph Lauren', category: 'Premium' },
  { name: 'RENATO BALESTRA', category: 'Premium' },
  { name: 'REPLAY', category: 'Populaire' },
  { name: 'ROBERT CASTEL', category: 'Autre' },
  { name: 'ROBERTO CARRAS', category: 'Autre' },
  { name: 'ROBERTO CAVALLI', category: 'Premium' },
  { name: 'Rodenstock', category: 'Autre' },
  { name: 'ROSALBA', category: 'Autre' },
  { name: 'S.T. Dupont', category: 'Premium' },
  { name: 'SAINT MICHEL', category: 'Française' },
  { name: 'SHOAL', category: 'Autre' },
  { name: 'Sillouette', category: 'Autre' },
  { name: 'SIMPLE', category: 'Autre' },
  { name: 'SOLEKO', category: 'Autre' },
  { name: 'SOLOTICA', category: 'Autre' },
  { name: 'STELLA McCARTNEY', category: 'Premium' },
  { name: 'STEPPER TITANIUM', category: 'Autre' },
  { name: 'SWAROVSKI', category: 'Premium' },
  { name: 'TAG', category: 'Premium' },
  { name: 'THE LINE', category: 'Autre' },
  { name: 'TIFFANY', category: 'Premium' },
  { name: 'TIFFANY & CO', category: 'Premium' },
  { name: 'TIMBERLAND', category: 'Populaire' },
  { name: 'TITTO BLUNI', category: 'Autre' },
  { name: 'TOMMY HILFIGER', category: 'Populaire' },
  { name: 'TREE', category: 'Autre' },
  { name: 'Valentino', category: 'Premium' },
  { name: 'VANNI', category: 'Autre' },
  { name: 'VASCO DE GAMA', category: 'Autre' },
  { name: 'VISION OPTIQUE', category: 'Autre' },
  { name: 'VISTALIA FASHION', category: 'Autre' },
  { name: 'Vogue', category: 'Populaire' },
  { name: 'WEB', category: 'Autre' },
  { name: 'WEST', category: 'Autre' },
  { name: 'Xelis', category: 'Autre' },
  { name: 'YVES SAINT LAURENT', category: 'Premium' },
  { name: 'ZEISS', category: 'Autre' },
  { name: '2-LIGHT', category: 'Autre' },
  { name: 'AB LENS', category: 'Autre' },
  { name: 'ADELMI', category: 'Autre' },
  { name: 'ADORE', category: 'Autre' },
  { name: 'ALCON', category: 'Autre' },
  { name: 'ARMANI EXCHANGE', category: 'Populaire' },
  { name: 'AUGUSTO VALENTINI', category: 'Premium' },
  { name: 'AVEO', category: 'Autre' },
  { name: 'AVIZOR', category: 'Autre' },
  { name: 'Bausch & Lomb', category: 'Autre' },
  { name: 'BBGR', category: 'Autre' },
  { name: 'BELLA', category: 'Autre' },
  { name: 'BIRKA', category: 'Autre' },
  { name: 'BLUMARINE', category: 'Premium' },
  { name: 'BOSS', category: 'Premium' },
  { name: 'BOUCHERON', category: 'Premium' },
  { name: 'BUNOVIATA', category: 'Autre' },
  { name: 'CARLO ROSSI', category: 'Autre' },
  { name: 'CECI', category: 'Autre' },
  { name: 'Ciba Vision', category: 'Autre' },
  { name: 'COACH', category: 'Premium' },
  { name: 'COLLECTION CREATIVE', category: 'Autre' },
  { name: 'COOPER VISION', category: 'Autre' },
  { name: 'COTTET', category: 'Autre' },
  { name: 'D&T', category: 'Autre' },
  { name: 'DSQUARED', category: 'Premium' },
  { name: 'EASY EYEWEAR', category: 'Populaire' },
  { name: 'ELCE', category: 'Autre' },
  { name: 'EMILIO PUCCI', category: 'Premium' },
  { name: 'ESCADA', category: 'Premium' },
  { name: 'Essilor', category: 'Autre' },
  { name: 'EXALTO', category: 'Autre' },
  { name: 'EXTE', category: 'Autre' },
  { name: 'FACELOOX', category: 'Autre' },
  { name: 'FASHION TV', category: 'Autre' },
  { name: 'FERRAGAMO', category: 'Premium' },
  { name: 'FERRARI', category: 'Premium' },
  { name: 'FERRE', category: 'Premium' },
  { name: 'FINEWEAR', category: 'Autre' },
  { name: 'FP', category: 'Autre' },
  { name: 'FURLA', category: 'Premium' },
  { name: 'FYSH', category: 'Autre' },
  { name: 'GANT', category: 'Populaire' },
  { name: 'GF FERRE', category: 'Premium' },
  { name: 'Giorgio Armani', category: 'Premium' },
  { name: 'Givenchy', category: 'Premium' },
  { name: 'GUEST', category: 'Autre' },
  { name: 'HENRY JULIEN', category: 'Française' },
  { name: 'INDO', category: 'Autre' },
  { name: 'INTEROJO', category: 'Autre' },
  { name: 'INVU', category: 'Autre' },
  { name: 'ITALIA INDEPENDENT', category: 'Autre' },
  { name: 'JIMMY CHOO', category: 'Premium' },
  { name: 'JOE KENT', category: 'Autre' },
  { name: 'Johnson & Johnson', category: 'Autre' },
  { name: 'JUST CAVALLI', category: 'Premium' },
  { name: 'LACOSTE', category: 'Populaire' },
  { name: 'LEOPARD', category: 'Autre' },
  { name: 'LEVIS', category: 'Populaire' },
  { name: 'LIAISON', category: 'Autre' },
  { name: 'LIGHTEC', category: 'Autre' },
  { name: 'LIGIERS', category: 'Autre' },
  { name: 'LN OPTIC', category: 'Autre' },
  { name: 'LOZZA', category: 'Autre' },
  { name: 'LUXOTTICA', category: 'Autre' },
  { name: 'MARC JACOBS', category: 'Premium' },
  { name: 'MAX MARA', category: 'Premium' },
  { name: 'Mega Optic', category: 'Autre' },
  { name: 'MEGALENS', category: 'Autre' },
  { name: 'MEGALENS-FREQUENCY', category: 'Autre' },
  { name: 'MENICON', category: 'Autre' },
  { name: 'MICHAEL KORS', category: 'Premium' },
  { name: 'MINIMA', category: 'Française' },
  { name: 'MISS SIXTY', category: 'Populaire' },
  { name: 'MONT BLANC', category: 'Premium' },
  { name: 'Morel', category: 'Française' },
  { name: 'Mottler', category: 'Autre' },
  { name: 'NATURE COLOR', category: 'Autre' },
  { name: 'NUOVO EMPORIO', category: 'Autre' },
  { name: 'OEO', category: 'Autre' },
];
